package com.sbz;

import com.sbz.proj.model.*;

global java.util.logging.Logger LOGGER

rule "FULL_HOUSE_1_4"
    no-loop
    when
        $possibility: Possibility(
            card1.rank == card2.rank,
            card2.rank == card3.rank,

            card4.rank == card5.rank,
            sameSuit() == false,
            $pokerHand: pokerHand
        )
    then
        modify($possibility){
            pokerHand = PokerHand.FULL_HOUSE,
            additionalInfo.put("trips-index", 0),
            additionalInfo.put("pair-index", 3),
            weKnow = true
        }
end

rule "FULL_HOUSE_1_3"
    no-loop
    when
        $possibility: Possibility(
            card1.rank == card2.rank,

            card3.rank == card4.rank,
            card4.rank == card5.rank,
            sameSuit() == false,
            $pokerHand: pokerHand
        )
    then
        modify($possibility){
            pokerHand = PokerHand.FULL_HOUSE,
            additionalInfo.put("trips-index", 2),
            additionalInfo.put("pair-index", 0),
            weKnow = true
        }
end