package com.sbz;

import com.sbz.proj.model.*;

global java.util.logging.Logger LOGGER

rule "PAIR_1_2"
    no-loop
    when
        $possibility: Possibility(
            !weKnow,
            card1.rank == card2.rank,
            howManyWithRank(card1.rank) == 2,
            sameSuit() == false,
            $pokerHand: pokerHand
        )
    then
        modify($possibility){pokerHand = PokerHand.PAIR}
        //LOGGER.info("Imas royal flush");
end

rule "PAIR_2_3"
    no-loop
    when
        $possibility: Possibility(
            !weKnow,
            card2.rank == card3.rank,
            howManyWithRank(card2.rank) == 2,
            sameSuit() == false,
            $pokerHand: pokerHand
        )
    then
        modify($possibility){pokerHand = PokerHand.PAIR, weKnow = true}
end

rule "PAIR_3_4"
    no-loop
    when
        $possibility: Possibility(
            !weKnow,
            card3.rank == card4.rank,
            howManyWithRank(card3.rank) == 2,
            sameSuit() == false,
            $pokerHand: pokerHand
        )
    then
        modify($possibility){pokerHand = PokerHand.PAIR, weKnow = true}
end

rule "PAIR_4_5"
    no-loop
    when
        $possibility: Possibility(
            !weKnow,
            card4.rank == card5.rank,
            howManyWithRank(card4.rank) == 2,
            sameSuit() == false,
            $pokerHand: pokerHand
        )
    then
        modify($possibility){pokerHand = PokerHand.PAIR, weKnow = true}
end