package com.sbz;

import com.sbz.proj.model.*;

global java.util.logging.Logger LOGGER

declare BluffingEvent
    @role(event)
    action : Action
end

declare BluffingPreventEvent
    @role(event)
    action : Action
end

rule "All in when you have royal flush"
    lock-on-active true
    agenda-group "river"
	when
        $state: TableState(
            $players: players,
            $player: players.get(0),
            $player.getAction().get(0) == Action.NONE
        )
        $possibility: Possibility(
			best == true,
            $pokerHand: pokerHand == PokerHand.ROYAL_FLUSH
        )
		$possibilities : List() from collect(Possibility())
    then
        modify($state){
            getPlayers().get(0).getAction().set(0, Action.ALL_IN);
        }
		insert(Action.ALL_IN);
		delete($possibilities.get(0));
		delete($possibilities.get(1));
		delete($possibilities.get(2));
		delete($possibilities.get(3));
		delete($possibilities.get(4));
		delete($possibilities.get(5));
		delete($possibilities.get(6));
		delete($possibilities.get(7));
		delete($possibilities.get(8));
		delete($possibilities.get(9));
		delete($possibilities.get(10));
		delete($possibilities.get(11));
		delete($possibilities.get(12));
		delete($possibilities.get(13));
		delete($possibilities.get(14));
		delete($possibilities.get(15));
		delete($possibilities.get(16));
		delete($possibilities.get(17));
		delete($possibilities.get(18));
		delete($possibilities.get(19));
		delete($possibilities.get(20));
		delete($state);
end

rule "All in when you have a good combination"
    lock-on-active true
    agenda-group "river"
	when
        $state: TableState(
            $players: players,
            $player: players.get(0),
            $player.getAction().get(0) == Action.NONE
        )
        $possibility: Possibility(
            pokerHand != PokerHand.ROYAL_FLUSH,
			best == true,
            $pokerHand: pokerHand,
            pokerHand.strength >= 4
        )
		$possibilities : List() from collect(Possibility())
    then
        modify($state){
            getPlayers().get(0).getAction().set(0, Action.ALL_IN);
        }
		insert(Action.ALL_IN);
		LOGGER.info("You have " + $pokerHand.name());
		delete($possibilities.get(0));
		delete($possibilities.get(1));
		delete($possibilities.get(2));
		delete($possibilities.get(3));
		delete($possibilities.get(4));
		delete($possibilities.get(5));
		delete($possibilities.get(6));
		delete($possibilities.get(7));
		delete($possibilities.get(8));
		delete($possibilities.get(9));
		delete($possibilities.get(10));
		delete($possibilities.get(11));
		delete($possibilities.get(12));
		delete($possibilities.get(13));
		delete($possibilities.get(14));
		delete($possibilities.get(15));
		delete($possibilities.get(16));
		delete($possibilities.get(17));
		delete($possibilities.get(18));
		delete($possibilities.get(19));
		delete($possibilities.get(20));
		delete($state);
end

rule "Call in river when you have 2 pairs and opponents haven't raised more than 1.5 times your pot"
    lock-on-active true
    agenda-group "river"
	when
        $state: TableState(
            $players: players,
            $player: players.get(0),
            $player.getAction().get(0) == Action.NONE
        )
        $possibility: Possibility(
            $pokerHand: pokerHand,
			best == true,
            $pokerHand == PokerHand.TWO_PAIRS
        )
		$possibilities : List() from collect(Possibility())
        accumulate( Player($pot : getMoney(), $action : getAction().get(0) == Action.RAISE || getAction().get(0) == Action.BET) from $players, 
			$maxMoney : max($pot), $raiseCount : count($action); $raiseCount > 0)
        Player(moneyRatio($maxMoney.doubleValue()) <= 1.5) from $player
    then
        modify($state){
            getPlayers().get(0).getAction().set(0, Action.CALL);
        }
		insert(Action.CALL);
		LOGGER.info("You have " + $pokerHand.name());
        LOGGER.info("You should call to "+ $maxMoney);
		delete($possibilities.get(0));
		delete($possibilities.get(1));
		delete($possibilities.get(2));
		delete($possibilities.get(3));
		delete($possibilities.get(4));
		delete($possibilities.get(5));
		delete($possibilities.get(6));
		delete($possibilities.get(7));
		delete($possibilities.get(8));
		delete($possibilities.get(9));
		delete($possibilities.get(10));
		delete($possibilities.get(11));
		delete($possibilities.get(12));
		delete($possibilities.get(13));
		delete($possibilities.get(14));
		delete($possibilities.get(15));
		delete($possibilities.get(16));
		delete($possibilities.get(17));
		delete($possibilities.get(18));
		delete($possibilities.get(19));
		delete($possibilities.get(20));
		delete($state);  
end

rule "Call in river when you have only strong pocket pair"
    lock-on-active true
    agenda-group "river"
	when
        $state: TableState(
            $players: players,
            $player: players.get(0),
            $player.getAction().get(0) == Action.NONE,
            $player.getCard1().rank.rank == $player.getCard2().rank.rank,
            $player.getCard1().rank.rank + $player.getCard2().rank.rank >= 20
        )
        $possibility: Possibility(
            $pokerHand: pokerHand,
			best == true,
            pokerHand == PokerHand.PAIR
        )
		$possibilities : List() from collect(Possibility())
        accumulate( Player($pot : getMoney(), $action : getAction().get(0) == Action.RAISE || getAction().get(0) == Action.BET) from $players, 
			$maxMoney : max($pot), $raiseCount : count($action); $raiseCount > 0)
        Player(moneyRatio($maxMoney.doubleValue()) <= 1.3) from $player
    then
        modify($state){
            getPlayers().get(0).getAction().set(0, Action.CALL);
        }
		insert(Action.CALL);
		LOGGER.info("You have " + $pokerHand.name());
        LOGGER.info("You should call to "+ $maxMoney);
		delete($possibilities.get(0));
		delete($possibilities.get(1));
		delete($possibilities.get(2));
		delete($possibilities.get(3));
		delete($possibilities.get(4));
		delete($possibilities.get(5));
		delete($possibilities.get(6));
		delete($possibilities.get(7));
		delete($possibilities.get(8));
		delete($possibilities.get(9));
		delete($possibilities.get(10));
		delete($possibilities.get(11));
		delete($possibilities.get(12));
		delete($possibilities.get(13));
		delete($possibilities.get(14));
		delete($possibilities.get(15));
		delete($possibilities.get(16));
		delete($possibilities.get(17));
		delete($possibilities.get(18));
		delete($possibilities.get(19));
		delete($possibilities.get(20));
		delete($state);
end

rule "Fold in river when you have weak pair and someone raised over 1.3 times your own pot"
    lock-on-active true
    agenda-group "river"
	when
        $state: TableState(
            $players: players,
            $player: players.get(0),
            $player.getAction().get(0) == Action.NONE,
            $player.getCard1().rank.rank == $player.getCard2().rank.rank,
			$player.getCard1().rank.rank < 10
        )
        $possibility: Possibility(
            $pokerHand: pokerHand,
			best == true,
            pokerHand == PokerHand.PAIR
        )
		$possibilities : List() from collect(Possibility())
        accumulate( Player($pot : getMoney(), $action : getAction().get(0) == Action.RAISE || getAction().get(0) == Action.BET) from $players, 
			$maxMoney : max($pot), $raiseCount : count($action); $raiseCount > 0)
        Player(moneyRatio($maxMoney.doubleValue()) > 1.3) from $player
    then
        modify($state){
            getPlayers().get(0).getAction().set(0, Action.FOLD);
        }
		insert(Action.FOLD);
		insert(new ActionInsertEvent(new Date(), Action.FOLD));
		LOGGER.info("You have " + $pokerHand.name());
        LOGGER.info(", a weak one, you should fold.");
		delete($possibilities.get(0));
		delete($possibilities.get(1));
		delete($possibilities.get(2));
		delete($possibilities.get(3));
		delete($possibilities.get(4));
		delete($possibilities.get(5));
		delete($possibilities.get(6));
		delete($possibilities.get(7));
		delete($possibilities.get(8));
		delete($possibilities.get(9));
		delete($possibilities.get(10));
		delete($possibilities.get(11));
		delete($possibilities.get(12));
		delete($possibilities.get(13));
		delete($possibilities.get(14));
		delete($possibilities.get(15));
		delete($possibilities.get(16));
		delete($possibilities.get(17));
		delete($possibilities.get(18));
		delete($possibilities.get(19));
		delete($possibilities.get(20));
		delete($state);
end

rule "Fold in river when you have nothing and someone raised"
    lock-on-active true
    agenda-group "river"
	when
        $state: TableState(
            $players: players,
            $player: players.get(0),
            players.get(0).getCard1().rank.rank >= 12 || players.get(0).getCard2().rank.rank >= 12,
            $player.getAction().get(0) == Action.NONE
        )
        $possibility: Possibility(
            $pokerHand: pokerHand,
			best == true,
            pokerHand.strength <= 1
        )
		$possibilities : List() from collect(Possibility())
        Player(getAction().get(0) == Action.RAISE || getAction().get(0) == Action.BET) from $players
    then
        modify($state){
            getPlayers().get(0).getAction().set(0, Action.FOLD);
        }
		insert(Action.FOLD);
		insert(new ActionInsertEvent(new Date(), Action.FOLD));
		LOGGER.info("You have " + $pokerHand.name());
        LOGGER.info("You should fold.");
		delete($possibilities.get(0));
		delete($possibilities.get(1));
		delete($possibilities.get(2));
		delete($possibilities.get(3));
		delete($possibilities.get(4));
		delete($possibilities.get(5));
		delete($possibilities.get(6));
		delete($possibilities.get(7));
		delete($possibilities.get(8));
		delete($possibilities.get(9));
		delete($possibilities.get(10));
		delete($possibilities.get(11));
		delete($possibilities.get(12));
		delete($possibilities.get(13));
		delete($possibilities.get(14));
		delete($possibilities.get(15));
		delete($possibilities.get(16));
		delete($possibilities.get(17));
		delete($possibilities.get(18));
		delete($possibilities.get(19));
		delete($possibilities.get(20));
		delete($state);
end

rule "Fold in river when you have nothing"
    agenda-group "river"
	when
        $state: TableState(
            $players: players,
            $player: players.get(0),
            $player.getAction().get(0) == Action.NONE
        )
        $possibility: Possibility(
            $pokerHand: pokerHand,
			best == true,
			$pokerHand == PokerHand.HIGH_CARD || $pokerHand == PokerHand.UNKNOWN
        )
		$possibilities : List() from collect(Possibility())
    then
        modify($state){
            getPlayers().get(0).getAction().set(0, Action.FOLD);
        }
		insert(Action.FOLD);
		insert(new ActionInsertEvent(new Date(), Action.FOLD));
		LOGGER.info("You have " + $pokerHand.name());
		delete($possibilities.get(0));
		delete($possibilities.get(1));
		delete($possibilities.get(2));
		delete($possibilities.get(3));
		delete($possibilities.get(4));
		delete($possibilities.get(5));
		delete($possibilities.get(6));
		delete($possibilities.get(7));
		delete($possibilities.get(8));
		delete($possibilities.get(9));
		delete($possibilities.get(10));
		delete($possibilities.get(11));
		delete($possibilities.get(12));
		delete($possibilities.get(13));
		delete($possibilities.get(14));
		delete($possibilities.get(15));
		delete($possibilities.get(16));
		delete($possibilities.get(17));
		delete($possibilities.get(18));
		delete($possibilities.get(19));
		delete($possibilities.get(20));
		delete($state);
end

rule "No one in river raised, check with an ok hand"
	agenda-group "river"
	when
		$state : TableState(
			$players: players,
            $player: players.get(0),
            $player.getAction().get(0) == Action.NONE
		)
		$possibility: Possibility(
            $pokerHand: pokerHand,
			best == true,
			$pokerHand.strength <= 4
        )
		$possibilities : List() from collect(Possibility())
		not(Player(getAction().get(0) == Action.RAISE || getAction().get(0) == Action.BET) from $players) 
	then
		modify($state){
            getPlayers().get(0).getAction().set(0, Action.CHECK);
        }
		insert(Action.CHECK);
		insert(new ActionInsertEvent(new Date(), Action.CHECK));
		LOGGER.info("You have " + $pokerHand.name()+ " on river, you should check");
		delete($possibilities.get(0));
		delete($possibilities.get(1));
		delete($possibilities.get(2));
		delete($possibilities.get(3));
		delete($possibilities.get(4));
		delete($possibilities.get(5));
		delete($possibilities.get(6));
		delete($possibilities.get(7));
		delete($possibilities.get(8));
		delete($possibilities.get(9));
		delete($possibilities.get(10));
		delete($possibilities.get(11));
		delete($possibilities.get(12));
		delete($possibilities.get(13));
		delete($possibilities.get(14));
		delete($possibilities.get(15));
		delete($possibilities.get(16));
		delete($possibilities.get(17));
		delete($possibilities.get(18));
		delete($possibilities.get(19));
		delete($possibilities.get(20));
		delete($state);  
end


rule "No one in river raised, raise with a good hand"
	agenda-group "river"
	when
		$state : TableState(
			$players: players,
            $player: players.get(0),
            $player.getAction().get(0) == Action.NONE
		)
		$possibility: Possibility(
            $pokerHand: pokerHand,
			best == true,
			$pokerHand.strength > 4
        )
		$possibilities : List() from collect(Possibility())
		not(Player(getAction().get(0) == Action.RAISE || getAction().get(0) == Action.BET) from $players) 
	then
		modify($state){
            getPlayers().get(0).getAction().set(0, Action.RAISE);
        }
		insert(Action.RAISE);
		LOGGER.info("You have " + $pokerHand.name()+ " on river, you should raise");
		delete($possibilities.get(0));
		delete($possibilities.get(1));
		delete($possibilities.get(2));
		delete($possibilities.get(3));
		delete($possibilities.get(4));
		delete($possibilities.get(5));
		delete($possibilities.get(6));
		delete($possibilities.get(7));
		delete($possibilities.get(8));
		delete($possibilities.get(9));
		delete($possibilities.get(10));
		delete($possibilities.get(11));
		delete($possibilities.get(12));
		delete($possibilities.get(13));
		delete($possibilities.get(14));
		delete($possibilities.get(15));
		delete($possibilities.get(16));
		delete($possibilities.get(17));
		delete($possibilities.get(18));
		delete($possibilities.get(19));
		delete($possibilities.get(20));
		delete($state);
end


rule "Bluffing in river"
	no-loop 
	agenda-group "river"
	when
		$riverEvent : StageEvent(stageName == StageName.RIVER)
		$a1: ActionInsertEvent()
        Number(intValue >= 3) from accumulate(
            $a2: ActionInsertEvent(
                this != $a1, 
                action == Action.FOLD || action == Action.CHECK, 
                this meets[10m] $a1
            ),
            count($a2)
        )
		$actions: List() from collect(ActionInsertEvent())
		$otherRiverEvents: List() from collect(StageEvent(stageName == StageName.RIVER))
	then
		System.out.println("You were playing defensively often, you should try to bluff now.");
		insert(Action.ALL_IN);
		insert(new BluffingEvent(Action.ALL_IN));
		delete($actions.get(0));
		delete($actions.get(1));
		delete($actions.get(2));
		delete($actions.get(3));
		delete($otherRiverEvents.get(0));
		delete($otherRiverEvents.get(1));
		delete($otherRiverEvents.get(2));
		delete($otherRiverEvents.get(3));
end

rule "Bluff prevent river"
	no-loop
	agenda-group "river"
	when
		$b1 : BluffingEvent($bluffAction : action)
		$b2 : BluffingEvent(this != $b1, this meets[5m] $b1)
	then
		insert(new BluffingPreventEvent(Action.CHECK));
		insert(Action.CHECK);
		delete($bluffAction);
		delete($b1);
		delete($b2);
end