package com.sbz;

import com.sbz.proj.model.*;

global java.util.logging.Logger LOGGER

rule "Dobio sam rucne keceve"
    when
        $kec: Player(card1.rank.rank == 1 && card2.rank.rank == 1)
    then
        //System.out.println("dobio sam rucne keceve");
        LOGGER.info("AAAAAAAALLLLLLLLLLLOOOOOOOOOOO");
        TableState state = new TableState();
        state.setCurrentStage(StageName.FLOP);
        insert(state);
end


rule "THE FLOP"
    when
        $state: TableState(currentStage == StageName.FLOP)
    then
        //System.out.println("THE FLOP");
        LOGGER.info("AAAAAAAALLLLLLLLLLLOOOOOOOOOOO iz flopa");
end





rule "ROYAL_FLUSH"
    no-loop
    when
        $possibility: Possibility(
            $card1: card1.rank == Rank.R10,
            $card2: card2.rank == Rank.JACK,
            $card3: card3.rank == Rank.QUEEN,
            $card4: card4.rank == Rank.KING,
            $card5: card5.rank == Rank.ACE,
            sameSuit() == true,
            $pokerHand: pokerHand
        )
    then
        modify($possibility){pokerHand = PokerHand.ROYAL_FLUSH}
        LOGGER.info("Imas royal flush");
end

rule "FLUSH"
    no-loop
    when
        $possibility: Possibility(
            sameSuit() == true,
            $pokerHand: pokerHand
        )
    then
        modify($possibility){pokerHand = PokerHand.FLUSH}
        //LOGGER.info("Imas royal flush");
end

rule "FOUR_OF_A_KIND_1_2_3_4"
    no-loop
    when
        $possibility: Possibility(
            card1.rank == card2.rank,
            card2.rank == card3.rank,
            card3.rank == card4.rank,
            sameSuit() == false,
            $pokerHand: pokerHand
        )
    then
        modify($possibility){pokerHand = PokerHand.FOUR_OF_A_KIND}
        //LOGGER.info("Imas royal flush");
end

rule "FOUR_OF_A_KIND_2_3_4_5"
    no-loop
    when
        $possibility: Possibility(
            card2.rank == card3.rank,
            card3.rank == card4.rank,
            card4.rank == card5.rank,
            sameSuit() == false,
            $pokerHand: pokerHand
        )
    then
        modify($possibility){pokerHand = PokerHand.FOUR_OF_A_KIND}
        //LOGGER.info("Imas royal flush");
end

rule "HIGH_CARD"
    no-loop
    when
        $possibility: Possibility(
            weKnow == false,
            howManyWithRank(card1.rank) == 1,
            howManyWithRank(card2.rank) == 1,
            howManyWithRank(card3.rank) == 1,
            howManyWithRank(card4.rank) == 1,
            howManyWithRank(card5.rank) == 1,
            sameSuit() == false,
            $pokerHand: pokerHand != PokerHand.STRAIGHT
        )
    then
        modify($possibility){pokerHand = PokerHand.HIGH_CARD, weKnow = true}
        //LOGGER.info("Imas royal flush");
end