package com.sbz;

import com.sbz.proj.model.*;

global java.util.logging.Logger LOGGER

rule "Dobio sam rucne keceve"
    when
        $kec: Player(card1.rank.rank == 1 && card2.rank.rank == 1)
    then
        //System.out.println("dobio sam rucne keceve");
        LOGGER.info("AAAAAAAALLLLLLLLLLLOOOOOOOOOOO");
        TableState state = new TableState();
        state.setCurrentStage(StageName.FLOP);
        insert(state);
end


rule "THE FLOP"
    when
        $state: TableState(currentStage == StageName.FLOP)
    then
        //System.out.println("THE FLOP");
        LOGGER.info("AAAAAAAALLLLLLLLLLLOOOOOOOOOOO iz flopa");
end


rule "ROYAL_FLUSH"
    no-loop
    when
        $possibility: Possibility(
            $card1: cards.get(0).rank == Rank.R10,
            $card2: cards.get(1).rank == Rank.JACK,
            $card3: cards.get(2).rank == Rank.QUEEN,
            $card4: cards.get(3).rank == Rank.KING,
            $card5: cards.get(4).rank == Rank.ACE,
            sameSuit(),
            $pokerHand: pokerHand
        )
    then
        modify($possibility){pokerHand = PokerHand.ROYAL_FLUSH}
        LOGGER.info("Imas royal flush");
end
